### ISSUE TITLE
Running minimize-requires.py for the whole project

### ISSUE THREAD

**Issue by anton-trunov** [JasonGross/coq-tools#40]
If I just run `minimize-requires.py` in a loop for all the Coq files of our project like so:
```shell
#!/bin/sh
for f in `grep ".*\.v" _CoqProject `;
do minimize-requires.py --in-place -f _CoqProject ${f}; done
```

I get errors like this one:

>Compiled library `namespace.libname` (in file /path/to/libname.vo) makes inconsistent assumptions over library `namespace.dependency`

I guess this wouldn't happen if we started minimizing from the leaves.

Is there an existing solution for this use case? Or could this be added as a feature? Thank you.

**Comment by JasonGross** [comment]
It shouldn't be to hard to fix this.  It's already possible to pass multiple files on the command line at once, and I should be able to write a couple of lines to sort them in dependency order.

Alternatively, I can ensure there's a way to output with a different extension / filename, so that the original .vo files aren't touched.

**Comment by anton-trunov** [comment]
From the user perspective I'd prefer something like
```shell
minimize-requires.py --in-place --all -f _CoqProject
```
or maybe `--all` could imply `--in-place`
```shell
minimize-requires.py --all -f _CoqProject
```

But, of course, it's your call 😀

**Comment by JasonGross** [comment]
Finally got around to implementing this.  You can now do
```
minimize-requires.py --all -f _CoqProject
```
and have it work.  Let me know if you run into any issues.
