### ISSUE TITLE
Use Admitted instead of admit tactic + Qed

### ISSUE THREAD

**Issue by SkySkimmer** [JasonGross/coq-tools#79]
It's a bit shorter and imo looks cleaner.

**Comment by JasonGross** [comment]
I think we should use the following heuristic:
- use `Admitted` for anything that ends in `Admitted` or `Qed`
- use `admit. Defined.` for anything that's not already `Admitted` (may catch cases where the above fails to work due to issues with the obligation tactic imposing universe constraints, etc)
- have a pass at the end, after there are no more files to inline, that tries `Admitted` for everything


Alternatively, maybe we should just first try `Admitted` for everything and then if that fails try `admit. Defined.`?

**Comment by JasonGross** [comment]
Note, btw, that the reason I used `admit` in the first place was to not introduce errors on `unfold` that used to work

**Comment by SkySkimmer** [comment]
I think cases where `admit. Defined.` works but `Admitted.` doesn't should be pretty rare. Other than uncovering bugs, the only case I can imagine is if there's something like `unfold foo` somewhere which doesn't actually rely on the definition of foo.

**Comment by JasonGross** [comment]
> I can imagine is if there's something like unfold foo somewhere which doesn't actually rely on the definition of foo.

I think this is a bit more common than you think; I have many general tactics that unfold multiple identifiers in the same tactic call, and these tactics are used in multiple proofs, each of which only requires some subset of the identifiers to be unfolded.

**Comment by SkySkimmer** [comment]
Then it may make more sense to have the pass at the end. The successful transformation to Admitted doesn't seem like it would unlock further removals.
